[package]
name = "aa"
version = "1.0.1"
cairo-version = "2.7.0"

[dependencies]
starknet = "2.7.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.27.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"